FROM resin/%%RESIN_MACHINE_NAME%%-debian

RUN apt-get update && apt-get install -y curl wget build-essential
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN ./build.sh %%RESIN_MACHINE_NAME%% '.*' example_module

CMD ./run.sh
